Models/Contact.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LendCar.Models
{
    public class Contact
    {
        public int Id { get; set; }
        public string  Email { get; set; }
        public string Phone { get; set; }
        public string Location { get; set; }
    }
}

ViewModels/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace LendCar.ViewModels
{
    public class ContactViewModel
    {
        [Required,EmailAddress,Display(Name ="Email")]
        public string UserEmail { get; set; }
        [Required, Display(Name = "Subject")]
        public string MailSubjct { get; set; }
        [Required, Display(Name = "Message")]
        public string Message { get; set; }
    }
}

Controllers/PaymentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LendCar.Models;
using LendCar.Repository;
using Microsoft.AspNetCore.Mvc;
using Stripe;

namespace LendCar.Controllers
{
    [Route("Payment")]
    public class PaymentController : Controller
    {
        public PaymentController(ICarRepository ICarRepository)
        {
            this.ICarRepository = ICarRepository;
        }

        public ICarRepository ICarRepository { get; }

        [Route("Pay")]
        public IActionResult Pay(VehicleBooking bookingInfo, decimal amount, string stripeEmail, string stripeToken)
        {

            var c = new CustomerService();
            var customer = c.Create(new CustomerCreateOptions()
            {
                Email = stripeEmail,
                Source = stripeToken
            });
            var ch = new ChargeService();
            var change = ch.Create(new ChargeCreateOptions
            {
                Amount =(long)amount*100,
                Currency = "egp",
                Description = "Vechile booking ",
                Customer = customer.Id,
                ReceiptEmail = stripeEmail
            });
            if (change.Status == "succeeded")
            {
                ICarRepository.VehicleBook(new VehicleBooking()
                {
                    HireDate= ICarRepository.ChangeDateFormatToDaysMonthYears(bookingInfo.HireDate),
                    ReturnData=ICarRepository.ChangeDateFormatToDaysMonthYears(bookingInfo.ReturnData),
                    VehicleId=bookingInfo.VehicleId,
                    RenterId=bookingInfo.RenterId
                });
                ICarRepository.Save();

                return RedirectToPage("/PaymentSuccess");
            }
            return RedirectToPage("/PaymentFail");
        }
    }
}

Pages/ExternalLogin.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using LendCar.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.Logging;

namespace LendCar.Pages
{
    [AllowAnonymous]
    public class ExternalLoginModel : PageModel
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger<ExternalLoginModel> _logger;

        public ExternalLoginModel(
            SignInManager<ApplicationUser> signInManager,
            UserManager<ApplicationUser> userManager,
            ILogger<ExternalLoginModel> logger)
        {
            _signInManager = signInManager;
            _userManager = userManager;
            _logger = logger;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public string LoginProvider { get; set; }

        public string ReturnUrl { get; set; }

        [TempData]
        public string ErrorMessage { get; set; }

        public class InputModel
        {
            [Required]
            [EmailAddress]
            public string Email { get; set; }
        }

        public IActionResult OnGetAsync()
        {
            return RedirectToPage("./Index");
        }

        public IActionResult OnPost(string provider, string returnUrl = null)
        {
            
            var redirectUrl = Url.Page("./ExternalLogin", pageHandler: "Callback", values: new { returnUrl });
            var properties = _signInManager.ConfigureExternalAuthenticationProperties(provider, redirectUrl);
            return new ChallengeResult(provider, properties);
        }

        public async Task<IActionResult> OnGetCallbackAsync(string returnUrl = null, string remoteError = null)
        {
            returnUrl = returnUrl ?? Url.Content("~/");
            if (remoteError != null)
            {
                ErrorMessage = $"Error from external provider: {remoteError}";
                return RedirectToPage("./Login", new { ReturnUrl = returnUrl });
            }
            var info = await _signInManager.GetExternalLoginInfoAsync();
            if (info == null)
            {
                ErrorMessage = "Error loading external login information.";
                return RedirectToPage("./Login", new { ReturnUrl = returnUrl });
            }

            // Sign in the user with this external login provider if the user already has a login.
            var result = await _signInManager.ExternalLoginSignInAsync(info.LoginProvider, info.ProviderKey, isPersistent: false, bypassTwoFactor: true);
            if (result.Succeeded)
            {
                _logger.LogInformation("{Name} logged in with {LoginProvider} provider.", info.Principal.Identity.Name, info.LoginProvider);
                return LocalRedirect(returnUrl);
            }
            if (result.IsLockedOut)
            {
                return RedirectToPage("./Lockout");
            }
            else
            {
                // If the user does not have an account, then ask the user to create an account.
                ReturnUrl = returnUrl;
                LoginProvider = info.LoginProvider;
                if (info.Principal.HasClaim(c => c.Type == ClaimTypes.Email))
                {
                    Input = new InputModel
                    {
                        Email = info.Principal.FindFirstValue(ClaimTypes.Email)
                    };
                }
                return RedirectToPage("./Index");
            }
        }

        public async Task<IActionResult> OnPostConfirmationAsync(string returnUrl = null)
        {
            returnUrl = returnUrl ?? Url.Content("~/");
            // Get the information about the user from the external login provider
            var info = await _signInManager.GetExternalLoginInfoAsync();
            if (info == null)
            {
                ErrorMessage = "Error loading external login information during confirmation.";
                return RedirectToPage("./Login", new { ReturnUrl = returnUrl });
            }

            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = Input.Email, Email = Input.Email };
                var result = await _userManager.CreateAsync(user);
                if (result.Succeeded)
                {
                    result = await _userManager.AddLoginAsync(user, info);
                    if (result.Succeeded)
                    {
                        await _signInManager.SignInAsync(user, isPersistent: false);
                        _logger.LogInformation("User created an account using {Name} provider.", info.LoginProvider);

                        var userId = await _userManager.GetUserIdAsync(user);
                        var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
                        code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
                        var callbackUrl = Url.Page(
                            "/Account/ConfirmEmail",
                            pageHandler: null,
                            values: new { area = "Identity", userId = userId, code = code },
                            protocol: Request.Scheme);
 
                        return LocalRedirect("./Index");
                    }
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            LoginProvider = info.LoginProvider;
            ReturnUrl = returnUrl;
            return RedirectToPage("./Index");
        }
    }
}

Pages/Home.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LendCar.Pages
{
    public class HomeModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Pages/HowUse.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LendCar.Pages
{
    public class HowUseModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LendCar.Models;
using LendCar.Repository;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Stripe;

namespace LendCar.Pages
{
    public class HomeModel : PageModel
    {
        private SignInManager<ApplicationUser> _signInManager;
        private ICarRepository _carRepo;
        public List<Vehicle> AvailableVehicles { get; set; }
        public List<Vehicle> AcceptedVehicles { get; set; }
        public HomeModel(SignInManager<ApplicationUser> signInManager, ICarRepository carRepo)
        {
            _signInManager = signInManager;
            _carRepo = carRepo;
        }
        public void OnGet()
        {
            AvailableVehicles = _carRepo.GetAllAvailableVechilces().ToList();
            AcceptedVehicles = _carRepo.GetAllVehiclesAccepted().OrderByDescending(v => v.Rate).Take(3).ToList();
        }

        public IActionResult OnGetLogout()
        {
            this._signInManager.SignOutAsync();
            return RedirectToPage("Index");
        }

    }
}

Pages/NotFound.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LendCar.Pages
{
    public class testModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Pages/Payment.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LendCar.Pages
{
    public class PaymentModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Pages/PaymentFail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LendCar.Pages.Shared
{
    public class PaymentFailModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Pages/PaymentSuccess.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LendCar.Pages.Shared
{
    public class PaymentSuccessModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Pages/UnknownError.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LendCar.Pages
{
    public class errorModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Pages/about.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LendCar.Pages
{
    public class aboutModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Pages/carDetails.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LendCar.Models;
using LendCar.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LendCar.Pages
{
    public class carDetailsModel : PageModel
    {
        public Vehicle CurrentCar { get; set; }
        public ApplicationUser Owner { get; set; }

        public List<Img> CurrentCarImges;
        public ICarRepository CarRepository { get; }
        public IUserRepository UserRepository { get; }

        public carDetailsModel(ICarRepository _CarRepository,IUserRepository _UserRepository)
        {
            CarRepository = _CarRepository;
            UserRepository = _UserRepository;
        }
        public void OnGet(string id)
        {
            CurrentCar = CarRepository.Find("1FTRW14W84KC76110");
            CurrentCarImges = CarRepository.GetImgForCurrntCar("1FTRW14W84KC76110");
            Owner =UserRepository.Find(CurrentCar.OwnerId);
        }
    }
}

Pages/contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LendCar.Models;
using LendCar.Repository;
using LendCar.ViewModels;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LendCar.Pages
{
    public class contactModel : PageModel
    {
        
        public Contact Contact { get; set; }
        public IContactRepository ContactRep { get; }
        public IEmail Email { get; }

        [BindProperty]
        public ContactViewModel ContactViewModel { get; set; }
        public contactModel(IContactRepository contactRep, IEmail email)
        {
            ContactRep = contactRep;
            Email = email;
            Contact = ContactRep.GetCompanyContact();
        }

        public  void OnPost()
        {
            if (ModelState.IsValid) 
            {
                 Email.SendEmail("mohamedesam9397@gmail.com", 
                    ContactViewModel.MailSubjct, ContactViewModel.UserEmail+"\n\n"+ContactViewModel. Message);
            }
        }
    }
}

Pages/error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LendCar.Pages
{
    public class errorModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Pages/failConfirme.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LendCar.Pages
{
    public class failConfirmeModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Pages/successConfirme.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LendCar.Pages
{
    public class successConfirmeModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Pages/test.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LendCar.Pages
{
    public class testModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Pages/userProfile.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LendCar.Pages
{
    public class userProfileModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Pages/ExternalLogin.cshtml
@page
@model ExternalLoginModel
@{
    ViewData["Title"] = "Register";
}

<h1>@ViewData["Title"]</h1>

<p class="text-info">
    You've successfully authenticated with <strong>@Model.LoginProvider</strong>.
</p>

<div class="row">
    <div class="col-md-4">
        <form asp-page-handler="Confirmation" asp-route-returnUrl="@Model.ReturnUrl" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Input.Email"></label>
                <input asp-for="Input.Email" class="form-control" />
                <span asp-validation-for="Input.Email" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">Register</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Pages/NotFound.cshtml
@page
@model LendCar.Pages.testModel
@{
    ViewData["Title"] = "Page Not Found";
}

<section class="main-container">
    <div class="container">
        <div class="row main-row">

            <div class="sade-face hidden-xs"></div>

            <div class="col-md-12 text-center">
                <div class="error-main-titel">
                    <h1>404</h1>
                </div>
                <div class="error-title-description">
                    <h3>OOPS... PAGE NOT FOUND!</h3>
                </div>
                <div class="help-text">
                    <p>Try using the button below to go to main page of the site</p> <br>
                    <a  asp-page="Index"><i class="fas fa-angle-double-left"></i> Back to Home Page</a>
                </div>
            </div>
        </div>
    </div>
</section>

Pages/Payment.cshtml
@page
@model LendCar.Pages.PaymentModel
@{
    ViewData["Title"] = "Payment";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

    <section class="paymentPage">
        <div class="container">
            <div class="row">
                <div class="paymentCont">
                    <div class="paymentWrap">
                        <div class="btn-group paymentBtnGroup btn-group-justified" data-toggle="buttons">
                            <label class="btn paymentMethod active">
                                <div class="method visa"></div>
                                <input type="radio" name="options" checked>
                            </label>
                            <label class="btn paymentMethod">
                                <div class="method master-card"></div>
                                <input type="radio" name="options">
                            </label>
                            <label class="btn paymentMethod">
                                <div class="method amex"></div>
                                <input type="radio" name="options">
                            </label>
                            <label class="btn paymentMethod">
                                <div class="method vishwa"></div>
                                <input type="radio" name="options">
                            </label>
                            <label class="btn paymentMethod">
                                <div class="method ez-cash"></div>
                                <input type="radio" name="options">
                            </label>

                            @*Model of Payment*@
                            <div class="modal fade product_view" id="Payment_view">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <a href="#" data-dismiss="modal" class="class pull-right"><span class="glyphicon glyphicon-remove" style="color:red"></span></a>
                                            <h3 class="modal-title">Payment</h3>
                                        </div>
                                        <div class="modal-body">
                                            <div class="container">
                                                <div class='row'>
                                                    <div class='col-md-4 col-md-offset-1'>
                                                        <script src='https://js.stripe.com/v2/' type='text/javascript'></script>
                                                        <form accept-charset="UTF-8" action="/" class="require-validation" data-cc-on-file="false" data-stripe-publishable-key="pk_bQQaTxnaZlzv4FnnuZ28LFHccVSaj" id="payment-form" method="post">
                                                            <div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="✓" /><input name="_method" type="hidden" value="PUT" /><input name="authenticity_token" type="hidden" value="qLZ9cScer7ZxqulsUWazw4x3cSEzv899SP/7ThPCOV8=" /></div>
                                                            <div class='form-row'>
                                                                <div class='col-xs-12 form-group required'>
                                                                    <label class='control-label'>Name on Card</label>
                                                                    <input class='form-control' size='4' type='text'>
                                                                </div>
                                                            </div>
                                                            <div class='form-row'>
                                                                <div class='col-xs-12 form-group card required'>
                                                                    <label class='control-label'>Card Number</label>
                                                                    <input autocomplete='off' class='form-control card-number' size='20' type='text'>
                                                                </div>
                                                            </div>
                                                            <div class='form-row'>
                                                                <div class='col-xs-4 form-group cvc required'>
                                                                    <label class='control-label'>CVC</label>
                                                                    <input autocomplete='off' class='form-control card-cvc' placeholder='ex. 311' size='4' type='text'>
                                                                </div>
                                                                <div class='col-xs-4 form-group expiration required'>
                                                                    <label class='control-label'>Expiration</label>
                                                                    <input class='form-control card-expiry-month' placeholder='MM' size='2' type='text'>
                                                                </div>
                                                                <div class='col-xs-4 form-group expiration required'>
                                                                    <label class='control-label'> </label>
                                                                    <input class='form-control card-expiry-year' placeholder='YYYY' size='4' type='text'>
                                                                </div>
                                                            </div>
                                                            <div class='form-row'>
                                                                <div class='col-md-12'>
                                                                    <div class='form-control total btn btn-info'>
                                                                        Total:
                                                                        <span class='amount'>$300</span>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div class='form-row'>
                                                                <div class='col-md-12 form-group'>
                                                                    <button class='form-control btn btn-primary submit-button' type='submit'>Pay »</button>
                                                                </div>
                                                            </div>
                                                            <div class='form-row'>
                                                                <div class='col-md-12 error form-group hide'>
                                                                    <div class='alert-danger alert'>
                                                                        Please correct the errors and try again.
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </form>
                                                    </div>
                                                    <div class='col-md-4'></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="footerNavWrap confirm clearfix">
                        <div class="btn btn-primary  pull-right btn-fyi" data-toggle="modal" data-target="#Payment_view">CHECKOUT<span class="glyphicon glyphicon-chevron-right"></span></div>
                    </div>
                </div>
            </div>
        </div>
    </section>

Pages/PaymentFail.cshtml
@page
@model LendCar.Pages.Shared.PaymentFailModel
@{
    ViewData["Title"] = "Payment Fail";
}

<section id="fail">
    <div class="container">
        <div class="row">
            <div class="col-md-6 text-center col-md-offset-3">
                <div class="fail">
                    <div class="fail-icon-box">
                        <i class="fas fa-times"></i>
                    </div>

                    <div class="fail-title">
                        <h3 class="modal-title">Error !</h3>
                    </div>

                    <div class="fail-message">
                        <p>Something went wrong. Please return to the previous page and try again.</p>
                    </div>

                    <a class="btn btn-success" asp-area="cars" asp-page="allCars"><i class="fas fa-backward"></i> Back To Home Page</a>
                </div>
            </div>
        </div>
    </div>
</section>

Pages/PaymentSuccess.cshtml
@page
@model LendCar.Pages.Shared.PaymentSuccessModel
@{
    ViewData["Title"] = "Payment Success";
}


<section id="success">
    <div class="container">
        <div class="row">
            <div class="col-md-6 text-center col-md-offset-3">
                <div class="success">
                    <div class="success-icon-box">
                        <i class="fas fa-check"></i>
                    </div>

                    <div class="success-title">
                        <h3 class="modal-title">Awesome !</h3>
                    </div>

                    <div class="success-message">
                        <p>Your booking has been confirmed. Check your email for detials.</p>
                    </div>

                    <a class="btn btn-success"  asp-area="cars" asp-page="allCars"><i class="fas fa-backward"></i> Back To Home Page</a>
                </div>
            </div>
        </div>
    </div>
</section>

Pages/UnknownError.cshtml
@page
@model LendCar.Pages.errorModel
@{
    ViewData["Title"] = "error";
}



<section class="main-container">
    <div class="container">
        <div class="row main-row">

            <div class="sade-face hidden-xs"></div>

            <div class="col-md-12 text-center">
                <div class="error-main-titel">
                    <h2 class="title-2">ERROR</h2>
                </div>
                <div class="error-title-description">
                    <h3 class="description-2">OOPS... Ther is an Error Occurred !</h3>
                </div>
                <div class="help-text">
                    <p>Try using the button below to go to main page of the site</p> <br>
                    <a href="#"><i class="fas fa-angle-double-left"></i> Back to Home Page</a>
                </div>
            </div>
        </div>
    </div>
</section>

 

Pages/failConfirme.cshtml
@page
@model LendCar.Pages.failConfirmeModel
@{
    ViewData["Title"] = "failConfirme";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}


<section id="fail">
    <div class="container">
        <div class="row">
            <div class="col-md-6 text-center col-md-offset-3">
                <div class="fail">
                    <div class="fail-icon-box">
                        <i class="fas fa-times"></i>
                    </div>

                    <div class="fail-title">
                        <h3 class="modal-title">Error !</h3>
                    </div>

                    <div class="fail-message">
                        <p>Something went wrong. Please return to the previous page and try again.</p>
                    </div>

                    <a class="btn btn-success" href="#"><i class="fas fa-backward"></i> Back To Home Page</a>
                </div>
            </div>
        </div>
    </div>
</section>

Pages/test.cshtml
@page
@model LendCar.Pages.testModel
@{
    ViewData["Title"] = "test";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<section class="main-container">
    <div class="container">
        <div class="row ">

            <div class="sade-face hidden-xs"></div>

            <div class="col-md-12 text-center">
                <div class="error-main-titel">
                    <h1>404</h1>
                </div>
                <div class="error-title-description">
                    <h3>OOPS... PAGE NOT FOUND!</h3>
                </div>
                <div class="help-text">
                    <p>Try using the button below to go to main page of the site</p> <br>
                    <a href="#"><i class="fas fa-angle-double-left"></i> Back to Home Page</a>
                </div>
            </div>
        </div>
    </div>
</section>